### ISSUE TITLE
Can you provide the code in the paper?

### ISSUE THREAD

**Issue by duxuan11** [WuJunde/PromptUNet#2]
Your paper has been accepted by journal, can you provide the code in the paper?

**Comment by WuJunde** [comment]
?  which journal this paper has been accepted?

**Comment by ChickenRushKR** [comment]
> ? which journal this paper has been accepted?

Wishing your code could be released soon

**Comment by duxuan11** [comment]
> ? which journal this paper has been accepted?

arxiv

**Comment by WuJunde** [comment]
https://github.com/MedicineToken/one-prompt
