### ISSUE TITLE
about the json file you provided

### ISSUE THREAD

**Issue by APointCharge** [WuJunde/PromptUNet#8]
i cant use the prompt_data.json file to recurrent your result.I noticed that you only used two datasets, ISIC2016 and REFUGE, but I am unable to use the JSON file you provided on ISIC2016. There are 900 images on ISIC2016, but JSON only has annotations for 135 images. The code will encounter errors during runtime. I don't know if you can solve this.
![a9af38b724cd722fa1a878d4afb714b](https://github.com/user-attachments/assets/9450bb98-20b2-4f89-855c-7211df22431a)

**Comment by WuJunde** [comment]
decathlon dataset is used for 3d datasets, not isic. I remembered I've written one specific data loader for isic, check the code

**Comment by APointCharge** [comment]
where can i download dataset_0.json?(the dataset_0.json in above picture is prompt_data.json which i changed name.)

**Comment by APointCharge** [comment]
> decathlon dataset is used for 3d datasets, not isic. I remembered I've written one specific data loader for isic, check the code

where can i download dataset_0.json?(the dataset_0.json in above picture is prompt_data.json which i changed name.)
